version: '3'

services:
  ttc-website:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - ttc-network

networks:
  ttc-network:
    driver: bridge
